site_name: TACTICS Simulator
repo_url: https://github.com/WoodOxen/tactics
docs_dir: Docs
edit_uri: 'blob/review/Docs/'
extra_css: [extra.css]
extra_javascript: [extra.js]
theme: readthedocs

nav:
- Home: 'index.md'
- Manual for Developers: "dev_index.md"
  - APIs: "dev_apis.md"

markdown_extensions:
  - admonition